/* tslint:disable */
/* eslint-disable */
export const __wasm_split_00parse_list_entries_495699008166880339400_export_c4ea92120dd89767e1a334504f7888df_parse_list_entries: (a: number, b: number, c: number) => void;
export const hydrate: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: number) => number;
export const intounderlyingbytesource_start: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: number) => number;
export const intounderlyingsink_close: (a: number) => number;
export const intounderlyingsink_write: (a: number, b: number) => number;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: number) => number;
export const memory: WebAssembly.Memory;
export const __indirect_function_table: WebAssembly.Table;
export const __wasm_bindgen_func_elem_7051: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_7860: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_10503: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_10503_2: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_10755: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
