/* tslint:disable */
/* eslint-disable */
export const __wasm_split_00parse_list_entries_79675364229865071000_export_3144c6a25ff84205b7c84ce88226046a_parse_list_entries: (a: number, b: number, c: number) => void;
export const hydrate: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: number) => number;
export const intounderlyingbytesource_start: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: number) => number;
export const intounderlyingsink_close: (a: number) => number;
export const intounderlyingsink_write: (a: number, b: number) => number;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: number) => number;
export const memory: WebAssembly.Memory;
export const __indirect_function_table: WebAssembly.Table;
export const __wasm_bindgen_func_elem_6358: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_8500: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_4504: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_4070: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_4504_3: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_2009: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_3395: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_8149: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
