/* tslint:disable */
/* eslint-disable */
export const hydrate: () => void;
export const __wasm_split_00parse_list_entries_495699008166880339400_export_673a3340222ef9dbca4f3e6a01045e5a_parse_list_entries: (a: number, b: number, c: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: number) => number;
export const intounderlyingsink_close: (a: number) => number;
export const intounderlyingsink_write: (a: number, b: number) => number;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: number) => number;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: number) => number;
export const intounderlyingbytesource_start: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const memory: WebAssembly.Memory;
export const __indirect_function_table: WebAssembly.Table;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h903a9ac0977ba0fbE: (a: number, b: number, c: number) => [number, number];
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h3712b95b5d34dab5E: (a: number, b: number, c: number, d: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17hf634d84be850c51fE: (a: number, b: number, c: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h77dd5573a8ca3a06E: (a: number, b: number, c: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h5669ba0a12261eafE: (a: number, b: number, c: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h1ef9bf5cb9ee9ab9E: (a: number, b: number) => number;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h20a74bbbcff66637E: (a: number, b: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h92f45605d3c99b3eE: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
