/* tslint:disable */
/* eslint-disable */
export const hydrate: () => void;
export const __wasm_split_00parse_list_entries_79675364229865071000_export_3144c6a25ff84205b7c84ce88226046a_parse_list_entries: (a: number, b: number, c: number) => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: number) => number;
export const intounderlyingbytesource_start: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: number) => number;
export const intounderlyingsink_close: (a: number) => number;
export const intounderlyingsink_write: (a: number, b: number) => number;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: number) => number;
export const memory: WebAssembly.Memory;
export const __indirect_function_table: WebAssembly.Table;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17he0c0dbf706401857E: (a: number, b: number, c: number) => [number, number];
export const _ZN12wasm_bindgen7convert8closures1_6invoke17hb9389d30aeded9daE: (a: number, b: number, c: number, d: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h589d09437bd1b2b0E: (a: number, b: number, c: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h439c50998b442413E: (a: number, b: number, c: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h654140c010afa9e0E: (a: number, b: number, c: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17he16d39720cd6c93fE: (a: number, b: number) => number;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17hff99780cf58d9ed7E: (a: number, b: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h6c37845d32f56765E: (a: number, b: number) => void;
export const _ZN12wasm_bindgen7convert8closures1_6invoke17h576776264485d906E: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
